package com.apollo.thefragments.ui.auth

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.ViewModelProvider
import com.apollo.thefragments.R
import com.apollo.thefragments.data.db.AppDatabase
import com.apollo.thefragments.repository.AuthRepository
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.material.tabs.TabLayout
import com.google.android.material.tabs.TabLayoutMediator
import androidx.viewpager2.widget.ViewPager2
import com.apollo.thefragments.MainActivity

class AuthActivity : AppCompatActivity() {

    lateinit var viewModel: AuthViewModel
    private lateinit var googleSignInClient: GoogleSignInClient

    companion object {
        const val RC_GOOGLE_SIGN_IN = 1001
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_auth)

        // ── Wire up MVVM ──────────────────────────────────────
        val db         = AppDatabase.getDatabase(this)
        val repository = AuthRepository(db.userDao(), db.sessionDao())
        val factory    = AuthViewModelFactory(repository)
        viewModel      = ViewModelProvider(this, factory)[AuthViewModel::class.java]

        // ── Google Sign-In setup ──────────────────────────────
        // default_web_client_id comes from google-services.json (auto-generated by the plugin)
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id))
            .requestEmail()
            .build()
        googleSignInClient = GoogleSignIn.getClient(this, gso)

        // ── ViewPager2 + TabLayout (Login / Register tabs) ────
        val viewPager = findViewById<ViewPager2>(R.id.view_pager)
        val tabLayout = findViewById<TabLayout>(R.id.tab_layout)
        viewPager.adapter = AuthPagerAdapter(this)
        TabLayoutMediator(tabLayout, viewPager) { tab, position ->
            tab.text = if (position == 0) "Login" else "Register"
        }.attach()

        // ── Observe auth results ──────────────────────────────
        // Both LoginFragment and RegisterFragment post to the same authResult LiveData
        viewModel.authResult.observe(this) { result ->
            if (result == "SUCCESS") {
                Toast.makeText(this, "Welcome!", Toast.LENGTH_SHORT).show()
                val intent = Intent(this, MainActivity::class.java)
                intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
                startActivity(intent)
                finish()
            } else {
                Toast.makeText(this, result, Toast.LENGTH_LONG).show()
            }
        }
    }

    // Called by LoginFragment when user taps "Sign in with Google"
    fun launchGoogleSignIn() {
        val signInIntent = googleSignInClient.signInIntent
        startActivityForResult(signInIntent, RC_GOOGLE_SIGN_IN)
    }

    // Google Sign-In returns here
    @Deprecated("Using for compatibility")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == RC_GOOGLE_SIGN_IN) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            try {
                val account = task.getResult(ApiException::class.java)
                // Pass the Google account to ViewModel → Repository → Firebase
                viewModel.loginWithGoogle(account)
            } catch (e: ApiException) {
                Toast.makeText(this, "Google sign-in failed: ${e.message}", Toast.LENGTH_SHORT).show()
            }
        }
    }
}
